import React from 'react';
import SearchInput, {createFilter} from 'react-search-input'
 

class SearchBox extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      searchTerm: ''
    }
    this.searchUpdated = this.searchUpdated.bind(this)
  }
  
  render () {
    const filteredEmails = names.filter(createFilter(this.state.searchTerm))
    
    return (
      <div>
        <SearchInput className="search-input" onChange={this.searchUpdated} />
        {filteredEmails.map(email => {
          return (
            <div className="mail" key={email}>
              <div className="from">{email}</div>
            </div>
          )
        })}
      </div>
    )
  }
 
  searchUpdated (term) {
    this.setState({searchTerm: term})
  }
}

export default SearchBox;

const names = [
	"Avondale",
	"Buckeye",
	"Chandler",
	"Cochise",
	"Dewey",
	"Dolan Springs",
	"El Mirage",
	"Flagstaff",
	"Camp Verde",
	"Cornville",
	"Cottonwood",
	"Fort Mohave",
	"Glendale",
	"Goodyear",
	"Grand Canyon",
	"Gilbert",
	"Green Valley",
	"Heber",
	"Hereford",
	"Holbrook",
	"Kayenta",
	"Kingman",
	"Litchfield Park",
	"Marana",
	"Mesa",
	"Page",
	"Paradise Valley",
	"Pearce",
	"Peoria",
	"Phoenix",
	"Prescott Valley",
	"Rimrock",
	"Sahuarita",
	"Sedona",
	"Sierra Vista",
	"Scottsdale",
	"Sun City",
	"Sun City West",
	"Surprise",
	"Tempe",
	"Tolleson",
	"Tombstone",
	"Tucson",
	"Yuma",
	"Agoura Hills",
	"Alameda",
	"Alamo",
	"Albany",
	"Alhambra",
	"Aliso Viejo",
	"Altadena",
	"American Canyon",
	"Anaheim",
	"Anderson",
	"Angwin",
	"Apple Valley",
	"Aptos",
	"Arcadia",
	"Artesia",
	"Atascadero",
	"Atwater",
	"Azusa",
	"Belmont",
	"Belvedere Tiburon",
	"Benicia",
	"Ben Lomond",
	"Berkeley",
	"Beverly Hills",
	"Big Pine",
	"Blue Lake",
	"Blythe",
	"Bonita",
	"Boulder Creek",
	"Brea",
	"Brisbane",
	"Buena Park",
	"Burbank",
	"Burlingame",
	"Camarillo",
	"Campbell",
	"Canoga Park",
	"Canyon Country",
	"Canyon Dam",
	"Capay",
	"Capistrano Beach",
	"Cardiff By The Sea",
	"Carlsbad",
	"Carmel",
	"Carmel Valley",
	"Carmichael",
	"Carson",
	"Castro Valley",
	"Cerritos",
	"Chatsworth",
	"Chester",
	"Chico",
	"Chino",
	"Chino Hills",
	"Chula Vista",
	"Citrus Heights",
	"Claremont",
	"Cloverdale",
	"Clovis",
	"Colfax",
	"Colton",
	"Compton",
	"Concord",
	"Corona",
	"Corona Del Mar",
	"Coronado",
	"Corte Madera",
	"Costa Mesa",
	"Cotati",
	"Covina",
	"Crescent City",
	"Culver City",
	"Cupertino",
	"Cypress",
	"Daggett",
	"Daly City",
	"Dana Point",
	"Davis",
	"Deer Park",
	"Diamond Bar",
	"Discovery Bay",
	"Dinuba",
	"Dodgertown",
	"Downey",
	"Duarte",
	"Dublin",
	"Durham",
	"El Centro",
	"El Cerrito",
	"Elk",
	"El Monte",
	"El Segundo",
	"Emeryville",
	"Encinitas",
	"Encino",
	"Escalon",
	"Escondido",
	"Eureka",
	"Fairfax",
	"Fairfield",
	"Fair Oaks",
	"Folsom",
	"Fontana",
	"Foresthill",
	"Forest Knolls",
	"Fountain Valley",
	"Fremont",
	"Fresno",
	"Fullerton",
	"Garberville",
	"Gardena",
	"Garden Grove",
	"Glendora",
	"Goleta",
	"Granada Hills",
	"Granite Bay",
	"Greenbrae",
	"Grover Beach",
	"Hacienda Heights",
	"Half Moon Bay",
	"Hanford",
	"Harbor City",
	"Hat Creek",
	"Hawthorne",
	"Hayward",
	"Hemet",
	"Hermosa Beach",
	"Huntington Beach",
	"Imperial Beach",
	"Inglewood",
	"Irvine",
	"Jamul",
	"La Canada Flintridge",
	"Ladera Ranch",
	"Lafayette",
	"Laguna Hills",
	"Laguna Niguel",
	"Lagunitas",
	"La Habra",
	"La Honda",
	"La Jolla",
	"Lake Elsinore",
	"Lakewood",
	"La Mesa",
	"La Mirada",
	"Lancaster",
	"La Puente",
	"Larkspur",
	"La Verne",
	"Lawndale",
	"Lemon Cove",
	"Lemon Grove",
	"Lemoore",
	"Lincoln",
	"Lindsay",
	"Livermore",
	"Lodi",
	"Lone Pine",
	"Long Beach",
	"Loomis",
	"Los Alamitos",
	"Los Altos",
	"Los Angeles",
	"Los Gatos",
	"Los Osos",
	"Lucerne",
	"Manhattan Beach",
	"Marina",
	"Marina Del Rey",
	"Martinez",
	"Marysville",
	"Mckinleyville",
	"Meadow Vista",
	"Menifee",
	"Menlo Park",
	"Merced",
	"Midway City",
	"Millbrae",
	"Mill Valley",
	"Millville",
	"Milpitas",
	"Mineral",
	"Mira Loma",
	"Miranda",
	"Mission Hills",
	"Mission Viejo",
	"Modesto",
	"Monrovia",
	"Montague",
	"Montara",
	"Montebello",
	"Monterey",
	"Monterey Park",
	"Montrose",
	"Moraga",
	"Morgan Hill",
	"Moss Beach",
	"Moss Landing",
	"Mountain Ranch",
	"Mountain View",
	"Myers Flat",
	"National City",
	"Newark",
	"Newbury Park",
	"Newcastle",
	"Newport Beach",
	"Newport Coast",
	"North Hills",
	"North Hollywood",
	"North Palm Springs",
	"Northridge",
	"Norwalk",
	"Novato",
	"Nuevo",
	"Oakdale",
	"Oakland",
	"Oak View",
	"Oceanside",
	"Old Station",
	"Ontario",
	"Orange",
	"Orangevale",
	"Orinda",
	"Pacifica",
	"Pacific Grove",
	"Pacific Palisades",
	"Palmdale",
	"Palo Alto",
	"Paradise",
	"Paramount",
	"Parker Dam",
	"Pasadena",
	"Petaluma",
	"Pico Rivera",
	"Placentia",
	"Playa Del Rey",
	"Playa Vista",
	"Pleasant Hill",
	"Pleasanton",
	"Pollock Pines",
	"Pomona",
	"Port Costa",
	"Port Hueneme",
	"Portola Valley",
	"Poway",
	"Quincy",
	"Ranchita",
	"Rancho Cordova",
	"Rancho Cucamonga",
	"Raymond",
	"Redding",
	"Redlands",
	"Redondo Beach",
	"Redwood City",
	"Reseda",
	"Rialto",
	"Ridgecrest",
	"Richmond",
	"Ripon",
	"Riverside",
	"Rocklin",
	"Rodeo",
	"Rosamond",
	"Rosemead",
	"Roseville",
	"Rowland Heights",
	"Sacramento",
	"Salinas",
	"San Anselmo",
	"San Bernardino",
	"San Bruno",
	"San Carlos",
	"San Clemente",
	"San Diego",
	"San Fernando",
	"San Francisco",
	"San Gabriel",
	"San Jose",
	"San Juan Capistrano",
	"San Leandro",
	"San Luis Obispo",
	"San Marcos",
	"San Mateo",
	"San Pablo",
	"San Pedro",
	"San Rafael",
	"San Ramon",
	"Santa Ana",
	"Santa Barbara",
	"Santa Clara",
	"Santa Clarita",
	"Santa Cruz",
	"Santa Maria",
	"Santa Monica",
	"Santa Rosa",
	"Saratoga",
	"Sausalito",
	"Scotts Valley",
	"Seal Beach",
	"Seaside",
	"Sebastopol",
	"Shafter",
	"Shasta Lake",
	"Sherman Oaks",
	"Signal Hill",
	"Smith River",
	"Solana Beach",
	"Solvang",
	"Somis",
	"South El Monte",
	"South Gate",
	"South Pasadena",
	"South San Francisco",
	"Spring Valley",
	"Springville",
	"Stanford",
	"Stinson Beach",
	"Stockton",
	"Studio City",
	"Suisun City",
	"Sunnyvale",
	"Sunol",
	"Sunset Beach",
	"Sun Valley",
	"Sylmar",
	"Tarzana",
	"Temple City",
	"The Sea Ranch",
	"Thousand Oaks",
	"Thousand Palms",
	"Topanga",
	"Torrance",
	"Tracy",
	"Trinidad",
	"Tujunga",
	"Turlock",
	"Tustin",
	"Union City",
	"Universal City",
	"Upland",
	"Valencia",
	"Vallejo",
	"Valley Village",
	"Van Nuys",
	"Venice",
	"Victorville",
	"Walnut",
	"Walnut Creek",
	"Walnut Grove",
	"West Covina",
	"West Hills",
	"West Hollywood",
	"Westminster",
	"West Point",
	"Westport",
	"West Sacramento",
	"Whittier",
	"Wildomar",
	"Willits",
	"Willow Creek",
	"Wilmington",
	"Windsor",
	"Winnetka",
	"Winters",
	"Woodacre",
	"Woodlake",
	"Woodland",
	"Woodland Hills",
	"Yorba Linda",
	"Yreka",
	"Yucaipa",
	"Alachua",
	"Altamonte Springs",
	"Anna Maria",
	"Altoona",
	"Archer",
	"Apollo Beach",
	"Atlantic Beach",
	"Baker",
	"Bartow",
	"Belleair Beach",
	"Big Pine Key",
	"Bokeelia",
	"Boca Raton",
	"Bonita Springs",
	"Bradenton",
	"Brandon",
	"Bradenton Beach",
	"Cantonment",
	"Brooksville",
	"Cape Coral",
	"Cape Canaveral",
	"Casselberry",
	"Clearwater Beach",
	"Clearwater",
	"Clewiston",
	"Clermont",
	"Cocoa",
	"Cortez",
	"Cocoa Beach",
	"Crystal River",
	"Dania",
	"Debary",
	"Deerfield Beach",
	"Delray Beach",
	"De Leon Springs",
	"Destin",
	"Deltona",
	"Dunedin",
	"Dundee",
	"Eastpoint",
	"Ellenton",
	"Estero",
	"Eustis",
	"Everglades City",
	"Fernandina Beach",
	"Fleming Island",
	"Fort Lauderdale",
	"Fort Myers",
	"Fort Walton Beach",
	"Goodland",
	"Gulf Breeze",
	"Haines City",
	"Hialeah",
	"High Springs",
	"Hobe Sound",
	"Hollywood",
	"Indialantic",
	"Indian Rocks Beach",
	"Islamorada",
	"Jacksonville Beach",
	"Jensen Beach",
	"Jupiter",
	"Holiday",
	"Howey In The Hills",
	"Inglis",
	"Key West",
	"Kissimmee",
	"Jacksonville",
	"Lady Lake",
	"Key Colony Beach",
	"Lake City",
	"Lakeland",
	"Lake Mary",
	"Lake Panasoffkee",
	"Lake Worth",
	"Largo",
	"Leesburg",
	"Lehigh Acres",
	"Longboat Key",
	"Longwood",
	"Lutz",
	"Maitland",
	"Marathon",
	"Marco Island",
	"Mary Esther",
	"Mayo",
	"Melbourne",
	"Melbourne Beach",
	"Mexico Beach",
	"Merritt Island",
	"Miami",
	"Miami Beach",
	"Middleburg",
	"Milton",
	"Miramar Beach",
	"Montverde",
	"Mulberry",
	"Naples",
	"Navarre",
	"Neptune Beach",
	"New Port Richey",
	"Niceville",
	"Nokomis",
	"North Fort Myers",
	"North Miami Beach",
	"Oldsmar",
	"Old Town",
	"Orange Park",
	"Orlando",
	"Oviedo",
	"Palm Bay",
	"Palm Beach Gardens",
	"Palm Coast",
	"Palm Harbor",
	"Panacea",
	"Panama City",
	"Panama City Beach",
	"Parrish",
	"Pensacola",
	"Pembroke Pines",
	"Perry",
	"Pinellas Park",
	"Polk City",
	"Pompano Beach",
	"Ponte Vedra",
	"Ponte Vedra Beach",
	"Port Charlotte",
	"Port Orange",
	"Port Richey",
	"Port Saint Joe",
	"Port Saint Lucie",
	"Riverview",
	"Rockledge",
	"Ruskin",
	"Safety Harbor",
	"Saint Augustine",
	"Saint Cloud",
	"Saint Petersburg",
	"Sanford",
	"Sanibel",
	"Santa Rosa Beach",
	"Sarasota",
	"Satellite Beach",
	"Satsuma",
	"Sebastian",
	"Seminole",
	"Sorrento",
	"Spring Hill",
	"Stuart",
	"Summerfield",
	"Summerland Key",
	"Sun City Center",
	"Tampa",
	"Tavernier",
	"The Villages",
	"Valrico",
	"Vero Beach",
	"Waldo",
	"Wellington",
	"Wesley Chapel",
	"Windermere",
	"Winter Garden",
	"Winter Park",
	"West Palm Beach",
	"Winter Springs",
	"Winter Haven",
	"Agawam",
	"Allston",
	"Amesbury",
	"Arlington",
	"Amherst",
	"Ashland",
	"Attleboro",
	"Barnstable",
	"Bedford",
	"Belchertown",
	"Beverly",
	"Boston",
	"Braintree",
	"Brewster",
	"Brighton",
	"Brockton",
	"Brookline",
	"Burlington",
	"Buzzards Bay",
	"Cambridge",
	"Charlestown",
	"Charlton",
	"Chelsea",
	"Chestnut Hill",
	"Chilmark",
	"Cummaquid",
	"Dalton",
	"Dedham",
	"Deerfield",
	"Dennis Port",
	"Dorchester",
	"Dorchester Center",
	"Eastham",
	"Easthampton",
	"East Wareham",
	"East Sandwich",
	"Edgartown",
	"Fairhaven",
	"Fall River",
	"Everett",
	"Falmouth",
	"Forestdale",
	"Framingham",
	"Gloucester",
	"Groton",
	"Hanson",
	"Harwich",
	"Harwich Port",
	"Holliston",
	"Hopkinton",
	"Hull",
	"Humarock",
	"Hyde Park",
	"Ipswich",
	"Hyannis",
	"Jamaica Plain",
	"Kingston",
	"Leicester",
	"Lexington",
	"Leverett",
	"Littleton",
	"Lowell",
	"Malden",
	"Lynn",
	"Marblehead",
	"Marshfield",
	"Marstons Mills",
	"Marlborough",
	"Mattapan",
	"Medford",
	"Mattapoisett",
	"Middleboro",
	"Milford",
	"Mill River",
	"Millis",
	"Nahant",
	"Natick",
	"Needham Heights",
	"New Bedford",
	"Newbury",
	"Newburyport",
	"Newton",
	"Newton Center",
	"Newton Highlands",
	"Newton Upper Falls",
	"Newton Lower Falls",
	"Northampton",
	"Northbridge",
	"North Dartmouth",
	"North Easton",
	"North Falmouth",
	"Northfield",
	"North Truro",
	"North Weymouth",
	"Norwood",
	"Oak Bluffs",
	"Onset",
	"Peabody",
	"Pepperell",
	"Pocasset",
	"Revere",
	"Roslindale",
	"Rowley",
	"Roxbury",
	"Roxbury Crossing",
	"Salem",
	"Sandisfield",
	"Sandwich",
	"Scituate",
	"Shrewsbury",
	"Sherborn",
	"Shutesbury",
	"Somerville",
	"Southborough",
	"South Dartmouth",
	"South Dennis",
	"South Hadley",
	"South Hamilton",
	"South Wellfleet",
	"South Yarmouth",
	"Springfield",
	"Sterling",
	"Sturbridge",
	"Sutton",
	"Swansea",
	"Truro",
	"Turners Falls",
	"Tyngsboro",
	"Vineyard Haven",
	"Wakefield",
	"Waltham",
	"Watertown",
	"Wayland",
	"Webster",
	"Wellesley Hills",
	"Wellfleet",
	"Wendell",
	"Wenham",
	"West Barnstable",
	"Westborough",
	"West Brookfield",
	"West Dennis",
	"Westford",
	"West Harwich",
	"West Hyannisport",
	"West Newton",
	"West Roxbury",
	"West Springfield",
	"West Tisbury",
	"West Yarmouth",
	"West Wareham",
	"Winthrop",
	"Woburn",
	"Worcester",
	"Arch Cape",
	"Astoria",
	"Bend",
	"Beaverton",
	"Blachly",
	"Blue River",
	"Brookings",
	"Butte Falls",
	"Camp Sherman",
	"Cannon Beach",
	"Clackamas",
	"Coos Bay",
	"Corvallis",
	"Cottage Grove",
	"Estacada",
	"Eugene",
	"Eagle Point",
	"Forest Grove",
	"Garibaldi",
	"Gladstone",
	"Gold Beach",
	"Gresham",
	"Hammond",
	"Happy Valley",
	"Hillsboro",
	"Hood River",
	"Idleyld Park",
	"Lake Oswego",
	"Langlois",
	"Mill City",
	"Molalla",
	"Newberg",
	"Newport",
	"North Bend",
	"Pendleton",
	"Portland",
	"Rainier",
	"Redmond",
	"Riddle",
	"Rogue River",
	"Roseburg",
	"Saint Helens",
	"Sandy",
	"Scio",
	"Shady Cove",
	"Sherwood",
	"South Beach",
	"Sublimity",
	"Troutdale",
	"Walton",
	"Wasco",
	"West Linn",
	"Wheeler",
	"Yamhill",
	"Alexandria",
	"Ambler",
	"Ardmore",
	"Aspers",
	"Aston",
	"Bellefonte",
	"Benton",
	"Berwyn",
	"Bethel Park",
	"Boalsburg",
	"Brookville",
	"Canadensis",
	"Carlisle",
	"Carnegie",
	"Clifton Heights",
	"Conestoga",
	"Conneaut Lake",
	"Connellsville",
	"Conshohocken",
	"Coraopolis",
	"Cranberry Twp",
	"Delta",
	"Denver",
	"Dingmans Ferry",
	"Drexel Hill",
	"Du Bois",
	"East Earl",
	"East Petersburg",
	"Eighty Four",
	"Enola",
	"Ephrata",
	"Erie",
	"Evans City",
	"Fairless Hills",
	"Flourtown",
	"Friedens",
	"Furlong",
	"Galeton",
	"Gibsonia",
	"Glenside",
	"Greeley",
	"Hanover",
	"Harrisburg",
	"Harrisville",
	"Hershey",
	"Highspire",
	"Hillsgrove",
	"Horsham",
	"Jamison",
	"Jenkintown",
	"Jersey Shore",
	"Kennett Square",
	"Kutztown",
	"Lafayette Hill",
	"Langhorne",
	"Lehighton",
	"Lemoyne",
	"Lewisburg",
	"Lititz",
	"Malvern",
	"Manheim",
	"Mechanicsburg",
	"Millrift",
	"Mill Run",
	"Morton",
	"Mount Gretna",
	"Mountville",
	"Narberth",
	"New Holland",
	"New Providence",
	"New Tripoli",
	"North Wales",
	"Oakmont",
	"Orangeville",
	"Palmerton",
	"Newville",
	"Pennsylvania Furnace",
	"Patton",
	"Philipsburg",
	"Philadelphia",
	"Phoenixville",
	"Pine Grove",
	"Pittsburgh",
	"Port Allegany",
	"Port Matilda",
	"Pottstown",
	"Renfrew",
	"Robesonia",
	"Rockwood",
	"Royersford",
	"Sharon Hill",
	"Shickshinny",
	"Souderton",
	"Spring Mills",
	"Strasburg",
	"State College",
	"Swarthmore",
	"Swiftwater",
	"Tidioute",
	"Upper Darby",
	"Upper Black Eddy",
	"Warren",
	"Washington",
	"Wayne",
	"West Chester",
	"Wickhaven",
	"Willow Street",
	"Wynnewood",
	"York",
	"Zion Grove",
	"Ashland City",
	"Beechgrove",
	"Bell Buckle",
	"Brentwood",
	"Chattanooga",
	"Clarksville",
	"College Grove",
	"Crossville",
	"Decherd",
	"Delano",
	"Del Rio",
	"Fayetteville",
	"Gatlinburg",
	"Goodlettsville",
	"Greenbrier",
	"Greeneville",
	"Harriman",
	"Heiskell",
	"Hendersonville",
	"Hermitage",
	"Hixson",
	"Joelton",
	"Jonesborough",
	"Kingston Springs",
	"Knoxville",
	"La Vergne",
	"Lobelville",
	"Louisville",
	"Martin",
	"Maryville",
	"Memphis",
	"Milan",
	"Mount Juliet",
	"Murfreesboro",
	"Nashville",
	"Nolensville",
	"Oak Ridge",
	"Old Hickory",
	"Pegram",
	"Pigeon Forge",
	"Santa Fe",
	"Savannah",
	"Sequatchie",
	"Sevierville",
	"Sharps Chapel",
	"Smyrna",
	"Soddy Daisy",
	"Sweetwater",
	"Tallassee",
	"Thompsons Station",
	"Townsend",
	"Tullahoma",
	"Unionville",
	"White House",
	"Abilene",
	"Aledo",
	"Alvin",
	"Amarillo",
	"Anahuac",
	"Argyle",
	"Bellaire",
	"Belton",
	"Bridge City",
	"Brownwood",
	"Buda",
	"Burleson",
	"Carrollton",
	"Cedar Hill",
	"Cedar Park",
	"Converse",
	"Coppell",
	"Corpus Christi",
	"Corrigan",
	"Crowley",
	"Denton",
	"Desoto",
	"El Paso",
	"Emory",
	"Flower Mound",
	"Friendswood",
	"Groves",
	"Grapevine",
	"Ingleside",
	"Keller",
	"Elm Mott",
	"Euless",
	"Haslet",
	"Hempstead",
	"Hewitt",
	"Fort Worth",
	"Lone Oak",
	"Frisco",
	"Luling",
	"Industry",
	"Katy",
	"Grand Prairie",
	"Harker Heights",
	"Mc Gregor",
	"La Marque",
	"Highlands",
	"League City",
	"Humble",
	"Houston",
	"Lewisville",
	"Midlothian",
	"Hutto",
	"Hurst",
	"Irving",
	"Joshua",
	"Magnolia",
	"Nolanville",
	"Manvel",
	"Lake Jackson",
	"Laredo",
	"Pilot Point",
	"Ledbetter",
	"Pointblank",
	"Midland",
	"Missouri City",
	"Manor",
	"Pflugerville",
	"Mckinney",
	"Plano",
	"Rowlett",
	"Mesquite",
	"Saint Hedwig",
	"Morgan",
	"San Saba",
	"North Richland Hills",
	"Round Rock",
	"Round Top",
	"San Juan",
	"Port Aransas",
	"Seabrook",
	"Texas City",
	"Silsbee",
	"Richardson",
	"Round Mountain",
	"Stafford",
	"Rogers",
	"Waco",
	"Texarkana",
	"Tomball",
	"Scroggins",
	"Shiner",
	"Sherman",
	"Wichita Falls",
	"Spring",
	"Sugar Land",
	"The Colony",
	"Whitesboro",
	"Carolina",
	"Bayamon",
	"Cidra",
	"Coamo",
	"Garrochales",
	"Juana Diaz",
	"Guaynabo",
	"Ponce",
	"Jayuya",
	"Vega Alta",
	"Punta Santiago",
	"Arlington Heights",
	"Bartlett",
	"Batavia",
	"Belleville",
	"Bloomington",
	"Blue Island",
	"Bolingbrook",
	"Buffalo Grove",
	"Champaign",
	"Chicago",
	"Chicago Ridge",
	"Cicero",
	"Des Plaines",
	"Dolton",
	"Downers Grove",
	"Dekalb",
	"East Dubuque",
	"Elmhurst",
	"Evanston",
	"Forest Park",
	"Glendale Heights",
	"Elmwood Park",
	"Glen Ellyn",
	"Hoffman Estates",
	"Lake Bluff",
	"Highland Park",
	"Herrin",
	"Libertyville",
	"Lake Villa",
	"Lincolnshire",
	"Lake Zurich",
	"Lombard",
	"Malta",
	"Manteno",
	"Melrose Park",
	"Mount Prospect",
	"Normal",
	"Oak Lawn",
	"O Fallon",
	"Morton Grove",
	"Naperville",
	"North Chicago",
	"Ottawa",
	"Palatine",
	"Palos Hills",
	"Peoria Heights",
	"River Forest",
	"Rockton",
	"Rolling Meadows",
	"Savanna",
	"Schaumburg",
	"Schiller Park",
	"Skokie",
	"Stone Park",
	"Streamwood",
	"Urbana",
	"Saint Charles",
	"Vienna",
	"Waukegan",
	"Wilmette",
	"Winfield",
	"Wheeling",
	"Wheaton",
	"Wonder Lake",
	"Zion"
]